### ISSUE TITLE
Tutorial data

### ISSUE THREAD

**Issue by arutik** [veghp/pyVDJ#1]
Hello!

Thanks for the package,

If you also upload to the repo the actual data files you work with in the tutorial, that would be really helpful (although they might be big, yes).

Sincerely,
Anna Arutyunyan

**Comment by veghp** [comment]
Thank you for your interest in the package.
Unfortunately I cannot do that at the moment, for multiple reasons (one being that github has a filesize limit).

I'll try and address this in the future.

**Comment by arutik** [comment]
Thanks! Understandable.
