### ISSUE TITLE
metadata issue

### ISSUE THREAD

**Issue by nicoac** [veghp/pyVDJ#2]
Hello. I'm setting up the manifest per the tutorial but running into an issue when writing the 'metadata'. Any suggestions?

manifest
Out[48]: 
           /VDJ/N4/filtered_contig_annotations.csv         n4
0       /VDJ/N4_KD/filtered_contig_annotations.csv      n4_kd
1      /VDJ/N4_CBT/filtered_contig_annotations.csv     n4_cbt
2   /VDJ/N4_KD_CBT/filtered_contig_annotations.csv  n4_kd_cbt
3          /VDJ/A2/filtered_contig_annotations.csv         a2
4       /VDJ/A2_KD/filtered_contig_annotations.csv      a2_kd
5      /VDJ/A2_CBT/filtered_contig_annotations.csv     a2_cbt
6   /VDJ/A2_KD_CBT/filtered_contig_annotations.csv  a2_kd_cbt
7          /VDJ/Y3/filtered_contig_annotations.csv         y3
8       /VDJ/Y3_KD/filtered_contig_annotations.csv      y3_kd
9      /VDJ/Y3_CBT/filtered_contig_annotations.csv     y3_cbt
10  /VDJ/Y3_KD_CBT/filtered_contig_annotations.csv  y3_kd_cbt
11         /VDJ/Q4/filtered_contig_annotations.csv         q4
12      /VDJ/Q4_KD/filtered_contig_annotations.csv      q4_kd
13     /VDJ/Q4_CBT/filtered_contig_annotations.csv     q4_cbt
14  /VDJ/Q4_KD_CBT/filtered_contig_annotations.csv  q4_kd_cbt

manifest = manifest[manifest['metadata'].isin(adata.obs['metadata'].unique())]
Traceback (most recent call last):

  File "<ipython-input-49-0cecc4265d13>", line 1, in <module>
    manifest = manifest[manifest['metadata'].isin(adata.obs['metadata'].unique())]

  File "/Users/u6027572/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)

  File "/Users/u6027572/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))

  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'metadata'

**Comment by veghp** [comment]
Thanks for trying this out. The error seems to be caused by that you don't have a 'metadata' column in your adata.obs pandas dataframe.

You can skip the manifest part and just make the `samples` python dict the way it is easiest for you.

The idea behind pyVDJ is that you create a dataframe in the AnnData object's .uns part, which contains the VDJ data. One of its columns stores cell names in the format cellbarcode_samplename . (Because two samples might share a cell barcode, cell barcode alone is not unique in the dataset.)
'cellbarcode' is taken from the csv files, and 'samplename' are the values in the `samples` dict. 
You will have to create a column in adata.obs that stores the cellnames in the same format: that's how pyVDJ will know which are the matching cells. I gave an example in the tutorial. The default columname is 'vdj_obs' but you can specify with the `'obs_col='`  argument of the `load_vdj()` function.  Hope this helps.

**Comment by nicoac** [comment]
Peter,

https://github.com/veghp/pyVDJ/issues/3#issuecomment-591357391

Your comment linked above actually solved my problems. Working through the rest of the data now. I appreciate your work.

Nico

**Comment by nicoac** [comment]
Peter,
Sorry to reopen this. Could you tell me how to add cdr3 to the adata for the Clonotype distribution? I'm a little unclear on this. 

From my adata.obs I set my meta = 'batch', 'n_genes', 'percent_mito', 'n_counts', 'leiden', 'leiden_anno', 'vdj_obs', 'vdj_has_vdjdata', 'vdj_clonotype', 'vdj_clone_count', 'vdj_is_clone', 'vdj_all_productive', 'vdj_any_productive', 'vdj_none_productive', 'vdj_chain_TRA', 'vdj_chain_TRB', 'vdj_chain_Multi', 'vdj_chain_IGH', 'vdj_chain_IGK', 'vdj_chain_None', 'vdj_constant_TRAC', 'vdj_constant_TRBC1', 'vdj_constant_None', 'vdj_constant_IGHE', 'vdj_v_TRAV12D-3', 'vdj_v_TRBV13-1', 'vdj_v_None', 'vdj_v_TRAV13-1', 'vdj_v_TRBV12-2', 'vdj_v_TRBV19', 'vdj_v_TRAV9-2', 'vdj_v_TRBV13-2', 'vdj_v_TRAV12N-1', 'vdj_v_TRAV9-1', 'vdj_v_TRBV3', 'vdj_v_TRAV3N-3', 'vdj_v_TRBV12-1', 'vdj_v_TRAV6-7-DV9', 'vdj_v_TRBV16', 'vdj_v_TRAV14N-1', 'vdj_v_TRAV3-3', 'vdj_v_TRAV13D-2', 'vdj_v_TRBV20', 'vdj_v_TRAV7D-4', 'vdj_v_TRAV5N-4', 'vdj_v_TRAV7N-4', 'vdj_v_TRBV14', 'vdj_v_TRBV15', 'vdj_v_TRAV9-4', 'vdj_v_TRBV5', 'vdj_v_TRAV7D-2', 'vdj_v_TRAV9N-3', 'vdj_v_TRAV4N-4', 'vdj_v_TRAV14N-3', 'vdj_v_TRAV16', 'vdj_v_TRAV9N-4', 'vdj_v_TRAV6-4', 'vdj_v_TRBV29', 'vdj_v_TRAV19', 'vdj_v_TRAV6-6', 'vdj_v_TRAV7-3', 'vdj_v_TRAV12-2', 'vdj_v_TRBV13-3', 'vdj_v_TRAV12D-2', 'vdj_v_TRBV2', 'vdj_v_TRAV9D-1', 'vdj_v_TRAV7-4', 'vdj_v_TRAV3D-3', 'vdj_v_TRAV6D-4', 'vdj_v_TRAV8D-1', 'vdj_v_TRBV31', 'vdj_v_TRAV13N-4', 'vdj_v_TRAV9N-2', 'vdj_v_TRAV8-1', 'vdj_v_TRAV6-1', 'vdj_v_TRAV6-2', 'vdj_v_TRBV1', 'vdj_v_TRAV10N', 'vdj_v_TRAV1', 'vdj_v_TRAV9D-4', 'vdj_v_TRAV10', 'vdj_v_TRAV5-4', 'vdj_v_TRAV6N-5', 'vdj_clonotype_n_40'

After that I ran the adata = pyvdj.stats(adata, meta), but I don't get a cdr3. Was this observation added at some other point?

Thanks!

**Comment by veghp** [comment]
You are supposed to set only one metadata category; and yes, 'donor' or 'metadata' was already in the example anndata object, these are annotations for the 10x samples. In your case it's 'leiden_anno' or the column containing n4, n4_kd ...

The CDR3 sequences are not added to adata.obs, because there is more than one CDR3 per cell. They are stored in dictionaries, e.g. `cdr3_dict` or `adata.uns['pyvdj']['cdr3']` as shown in the tutorial.

**Comment by nicoac** [comment]
Ok. I named my samples under 'batch' when I concatenated them using the anndata.concatenate() command. The issue I have now run into is that when I call my meta = 'batch' it errors out as follows:

ValueError: cannot index with vector containing NA / NaN values

My assumption is that this is due to the way I was reading in my samples by not using the manifest method you had and therefore left samples without VDJs. Do you have any suggestion as how to get around this error?

Thanks so much.

**Comment by veghp** [comment]
I don't have enough information to understand the problem, but it looks like not all cells are assigned a batch. The batch column should not have NA / NaN values, clearly each cell belongs to a batch.

**Comment by nicoac** [comment]
Did you concatenate your samples from the tutorial? Like:

`concatenated_data = AnnData.concatenate(sample1, sample2, join = 'outer', batch_categories = ['sample1', 'sample2'], index_unique = '-'`

**Comment by veghp** [comment]
I did not make the adata in the tutorial, just performed the analysis

But this is a way to do it:

    adatas = [sc.read_10x_mtx(filename, cache=True) for filename in filenames]  # where 'filenames' is a list of paths to the mtx files
    adata = adatas[0].concatenate(adatas[1:], join='inner', batch_key='sample_id', batch_categories=names, index_unique='-')  # where 'names' is a list of samplenames

**Comment by nicoac** [comment]
Thank you for your response Peter. I believe I may have found the issue though. I'm looking through the my obs.csv file and I think the fact that I loaded in my samples without using the manifest method is leaving in samples with no VDJ is the culprit. In the csv file columns I added following the tutorial I have cells that read 'no_data' when they have no VDJ = TRUE. In the tutorial you corrected that with this I believe:

`manifest = manifest[manifest['VDJ'].notnull()]`

Do you believe this could be the issue? And if so do you have a suggestion on how to remove them?
Thanks

**Comment by nicoac** [comment]
Just following up with what I've attempted to do. I've tried subsetting my Scanpy object by leaving in only the CD8 and CD4 T cells, where my cells of interest are by using the following and haven't had any luck yet.

`adata_new = adata[~adata.obs['clusters'].isin(['not t cells']),:].copy()`

**Comment by veghp** [comment]
From experience, it should work fine with samples that have no VDJ data, but all rows (cells) should have a value in the 'batch' column:

> I don't have enough information to understand the problem, but it looks like not all cells are assigned a batch. The batch column should not have NA / NaN values, clearly each cell belongs to a batch.

Have you checked that?

**Comment by nicoac** [comment]
Peter. Sorry for taking so long to respond and I appreciate your input. I reran the analysis and looking at the obs.csv that is generated every single row has a value in the batch column. I renamed it to sample_id. I don't know if it would be helpful to share this csv with you at all?

Hope you're doing well.

**Comment by veghp** [comment]
Yes, I can have a look at the csv file. You can find my email address [at genomefoundry.org](https://www.ed.ac.uk/biology/research/facilities/edinburgh-genome-foundry/who-we-are).

As this seems to be an analysis or Python question, rather than a bug in pyVDJ, perhaps we can continue via email and I will close this issue.

**Comment by nicoac** [comment]
Sounds good. Thank you Peter
