### ISSUE TITLE
Find VDJ usages and CDR3 for cells in specific leiden clusters

### ISSUE THREAD

**Issue by taopeng1100** [veghp/pyVDJ#6]
Can you help me in defining VDJ gene usages and CDR3 seq for cells in specific leiden clusters?

Thx!

Tao

**Comment by veghp** [comment]
The [tutorial](https://github.com/veghp/pyVDJ/tree/master/tutorials) has a section about retrieving CDR3 sequences: _Public, private and condition-specific clonotypes_
```python
meta = 'donor'  # here you specify the category for clustering
adata = pyvdj.stats(adata, meta)
cdr3 = adata.uns['pyvdj']['stats'][meta]['cdr3']
```
Details of the [stats() function here](https://github.com/veghp/pyVDJ/blob/760c80fb7c7ecad18cb78b0a66d42193e8609667/pyvdj/stats.py#L40). Then you can query the clusters, for example `set(cdr3['c1'])`. Alternatively, you can just take the original csv file with the VDJ data, and filter for the cells of interest. This requires no pyVDJ.

For gene usage, the scirpy package is probably a better choice. Another option is [Immunarch](https://immunarch.com/index.html). For example, [geneUsage()](https://immunarch.com/reference/geneUsage.html).

**Comment by taopeng1100** [comment]
meta = 'adata.obs[["leiden"]=="4"]'  # here you specify the category for clustering
adata = pyvdj.stats(adata, meta)
cdr3 = adata.uns['pyvdj']['stats'][meta]['cdr3']

I go the error:
KeyError Traceback (most recent call last) <ipython-input-50-6ce81aa53087> in <module> 1 meta = 'adata.obs[["leiden"]=="4"]' # here you specify the category for clustering ----> 2 adata = pyvdj.stats(adata, meta) 3 cdr3 = adata.uns['pyvdj']['stats'][meta]['cdr3'] ~\Anaconda3\lib\site-packages\pyvdj\stats.py in stats(adata, meta) 50 stats_dict['meta'] = meta 51 ---> 52 n_cells = adata.obs.groupby(meta).size() 53 n_hasvdj = adata.obs.groupby(meta)['vdj_has_vdjdata'].apply(sum) 54 stats_dict['cells'] = [n_cells, n_hasvdj] ~\Anaconda3\lib\site-packages\pandas\core\frame.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, observed) 5799 axis = self._get_axis_number(axis) 5800 -> 5801 return groupby_generic.DataFrameGroupBy( 5802 obj=self, 5803 keys=by, ~\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py in __init__(self, obj, keys, axis, level, grouper, exclusions, selection, as_index, sort, group_keys, squeeze, observed, mutated) 401 from pandas.core.groupby.grouper import get_grouper 402 --> 403 grouper, exclusions, obj = get_grouper( 404 obj, 405 keys, ~\Anaconda3\lib\site-packages\pandas\core\groupby\grouper.py in get_grouper(obj, key, axis, level, sort, observed, mutated, validate) 598 in_axis, name, level, gpr = False, None, gpr, None 599 else: --> 600 raise KeyError(gpr) 601 elif isinstance(gpr, Grouper) and gpr.key is not None: 602 # Add key to exclusions KeyError: 'adata.obs[["leiden"]=="4"]'


Tao

**Comment by veghp** [comment]
I believe it should be just `meta = 'leiden'` -- in my example, `donor` was the name of the category (column).
Then you should be able to list CDR3 in 4 with `cdr3['4'])`

**Comment by taopeng1100** [comment]
I think  I did not explain well. I have one sample. After UMAP clustering analysis, I have single cells into 12 clusters (leiden cluster). I like to see what are the clonotypes in cluster 4 with VDJ gene usages and CD3 seq.

Tao

**Comment by veghp** [comment]
I think you will need to get the list of cells in cluster 4, then filter the VDJ dataframe using these cells. Then you can have a look at the data/columns. I hope something like this helps (not tried):
```python
cluster4_cells = adata.obs.loc[adata.obs["leiden"].isin(["4"])]['vdj_obs'] .tolist()
    # where vdj_obs is the columnname you generated for loading in the data
vdjdf = adata.uns['pyvdj']['df']
vdj_cluster4 = vdjdf.loc[vdjdf['barcode_meta'].isin(cells)]
vdj_cluster4['cdr3']
```
However, it is probably better to use another up-to-date package. I'll archive this project because it is not maintained anymore.

**Comment by taopeng1100** [comment]
Appreciate your help!
